import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/contexts/AuthContext';
import { UserLocationProvider } from '@/contexts/UserLocationContext';
import { Inter } from 'next/font/google';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} bg-main-1 antialiased`}
        className={`${inter.className} bg-main-1 antialiased`}
      >
        <UserLocationProvider>
          <AuthProvider>{children}</AuthProvider>
        </UserLocationProvider>
      </body>
    </html>
  );
}
